# docker-compose.yml
version: '3.8'

services:
  customer-events-producer:
    build: .
    environment:
      - CONFLUENT_BOOTSTRAP_SERVERS=${CONFLUENT_BOOTSTRAP_SERVERS}
      - CONFLUENT_API_KEY=${CONFLUENT_API_KEY}
      - CONFLUENT_API_SECRET=${CONFLUENT_API_SECRET}
      - SCHEMA_REGISTRY_URL=${SCHEMA_REGISTRY_URL}
      - SCHEMA_REGISTRY_KEY=${SCHEMA_REGISTRY_KEY}
      - SCHEMA_REGISTRY_SECRET=${SCHEMA_REGISTRY_SECRET}
      - SERVICE_NAME=customer-events-producer
    command: python customer_events_producer.py
    restart: unless-stopped
    
  order-events-producer:
    build: .
    environment:
      - CONFLUENT_BOOTSTRAP_SERVERS=${CONFLUENT_BOOTSTRAP_SERVERS}
      - CONFLUENT_API_KEY=${CONFLUENT_API_KEY}
      - CONFLUENT_API_SECRET=${CONFLUENT_API_SECRET}
      - SCHEMA_REGISTRY_URL=${SCHEMA_REGISTRY_URL}
      - SCHEMA_REGISTRY_KEY=${SCHEMA_REGISTRY_KEY}
      - SCHEMA_REGISTRY_SECRET=${SCHEMA_REGISTRY_SECRET}
      - SERVICE_NAME=order-events-producer
    command: python order_events_producer.py
    restart: unless-stopped
    
  recommendation-engine:
    build: .
    environment:
      - CONFLUENT_BOOTSTRAP_SERVERS=${CONFLUENT_BOOTSTRAP_SERVERS}
      - CONFLUENT_API_KEY=${CONFLUENT_API_KEY}
      - CONFLUENT_API_SECRET=${CONFLUENT_API_SECRET}
      - SERVICE_NAME=recommendation-engine
    command: python recommendation_engine.py
    restart: unless-stopped
    
  fraud-detection:
    build: .
    environment:
      - CONFLUENT_BOOTSTRAP_SERVERS=${CONFLUENT_BOOTSTRAP_SERVERS}
      - CONFLUENT_API_KEY=${CONFLUENT_API_KEY}
      - CONFLUENT_API_SECRET=${CONFLUENT_API_SECRET}
      - SERVICE_NAME=fraud-detection
    command: python fraud_detection.py
    restart: unless-stopped